* Fix the wrong assumption in the autopkg tests that the OpenJDK is     the same as the default JDK.

diff --git a/debian/tests/jtreg-autopkgtest.in b/debian/tests/jtreg-autopkgtest.in
--- a/debian/tests/jtreg-autopkgtest.in
+++ b/debian/tests/jtreg-autopkgtest.in
@@ -11,9 +11,11 @@ fi
 
 host_arch=${DEB_HOST_ARCH:-$(dpkg --print-architecture)}
 
-export JTREG_HOME=/usr/share/java
-export JT_JAVA="${JT_JAVA:-/usr/lib/jvm/java-11-openjdk-${host_arch}}"
-JDK_DIR="${JDK_DIR:-$JT_JAVA}"
+# don't mess around with JT_* env vars. If JDK_TO_TEST is set, then the
+# script is called from the build, if not, from the autopkg tests
+if [ -z "$JDK_TO_TEST" ]; then
+  JDK_TO_TEST=$(echo @JDK_TO_TEST@ | sed "s/-[^-]*$/-$host_arch/")
+fi
 
 jtreg_version="$(dpkg-query -W jtreg | cut -f2)"
 
@@ -27,8 +29,8 @@ if dpkg --compare-versions ${jtreg_version} ge 4.2; then
 fi
   
 # check java binary
-if [ ! -x "${JDK_DIR}/bin/java" ]; then 
-  echo "Error: '${JDK_DIR}/bin/java' is not an executable." >&2
+if [ ! -x "${JDK_TO_TEST}/bin/java" ]; then
+  echo "Error: '${JDK_TO_TEST}/bin/java' is not an executable." >&2
   exit 1
 fi
 
@@ -46,7 +48,7 @@ jtreg_processes() {
 
 jtreg_pids() {
   ps x --no-headers -ww -o pid,ppid,args \
-    | awk "\$2 == 1 && \$3 ~ /^${JDK_DIR//\//\\/}/ {print \$1}"
+    | awk "\$2 == 1 && \$3 ~ /^${JDK_TO_TEST//\//\\/}/ {print \$1}"
 }
 
 cleanup() {
@@ -85,5 +87,5 @@ jtreg ${jt_options} \
   -timeout:5 \
   -workDir:"${AUTOPKGTEST_ARTIFACTS}/JTwork" \
   -reportDir:"${AUTOPKGTEST_ARTIFACTS}/JTreport" \
-  -jdk:${JDK_DIR} \
+  -jdk:${JDK_TO_TEST} \
   $@ 
