* OpenJDK 21 snapshot, Build 26.
  [ Vladimir Petko ]
  * d/p/*: refresh patches.
  * Copy OpenJDK 20 packaging changes:
    - d/rules: pack external debug symbols with build-id, do not pack duplicate
      symbols, do not strip JVM shared libraries (LP: #2012326, LP: #2016739).
    - d/{control, compat}: update debhelper-compat version, add jtreg7
      dependencies, regenerate control.
    - d/t/{jdk,hotspot,jaxp,lantools}: run tier1 and tier2 jtreg tests only,
      add test options from OpenJDK makefile.
    - d/t/*: fix test environment: add missing -nativepath (LP: #2001563).
    - d/t/jdk: provide dbus session for the window manager (LP: #2001576).
    - d/p/build_gtest.patch: build OpenJDK with the system googletest
      (LP: #2012316).
  * d/p/*: add patches for jtreg tests:
    - misalign-pointer-for-armhf.patch: packaging-specific patch to fix test
      failure introduced by d/p/m68k-support.diff.
    - log-generated-classes-test.patch: workaround JDK-8166162.
    - update-permission-test.patch: add security permissions for testng 7.
    - ldap-timeout-test-use-ip.patch, test-use-ip-address.patch:
      Ubuntu-specific patches to workaround missing DNS resolver on the build
      machines.
    - exclude_broken_tests.patch: quarantine failing tests.
  * Enable ppc64el JRE zero build as JDK-8299476 is fixed.
  * Known issues:
    - amd64: test/jdk/sun/security/pkcs11/KeyStore/CertChainRemoval.java:
      https://mail.openjdk.org/pipermail/jdk-dev/2023-May/007836.html
    - s390x: test/hotspot/jtreg/runtime/NMT/VirtualAllocCommitMerge.java:
      https://mail.openjdk.org/pipermail/hotspot-dev/2023-June/075316.html

  [ Matthias Klose ]
  * Fix jaxp.properties installation.
  * Bump standards version.

 -- Matthias Klose <doko@ubuntu.com>  Sat, 10 Jun 2023 17:54:09 +0200

diff --git a/debian/tests/jtreg-autopkgtest.in b/debian/tests/jtreg-autopkgtest.in
--- a/debian/tests/jtreg-autopkgtest.in
+++ b/debian/tests/jtreg-autopkgtest.in
@@ -18,6 +18,10 @@ if [ -z "${JDK_TO_TEST+x}" ]; then
   JDK_TO_TEST=$(echo @JDK_DIR@ | sed "s/-[^-]*$/-$host_arch/")
 fi
 
+if [ -z "${BOOTJDK_HOME+x}" ]; then
+  BOOTJDK_HOME=${JDK_TO_TEST}
+fi
+
 jtreg_version="$(dpkg-query -W @jtreg_pkg@ | cut -f2)"
 
 # set additional jtreg options
@@ -32,6 +36,11 @@ fi
 # check java binary
 if [ ! -x "${JDK_TO_TEST}/bin/java" ]; then
   echo "Error: '${JDK_TO_TEST}/bin/java' is not an executable." >&2
+  exit 1
+fi
+
+if [ ! -x "${BOOTJDK_HOME}/bin/java" ]; then
+  echo "Error: '${BOOTJDK_HOME}/bin/java' is not an executable." >&2
   exit 1
 fi
 
@@ -83,10 +92,11 @@ jtwork_dir="${AUTOPKGTEST_TMP}/${testsuite}/JTwork"
 output_dir="${AUTOPKGTEST_ARTIFACTS}/${testsuite}/"
 
 # retry tests with "fail" or "error" status at most 3 times
-for i in 0 1; do
+for i in 0 1 2; do
   # save each try under its own folder to preserve history
   report_path="${i}/JTreport"
   report_dir="${output_dir}/${report_path}"
+# see make/RunTests.gmk for a set of good options
   jtreg ${jt_options} \
     -verbose:summary \
     -automatic \
@@ -97,6 +107,8 @@ for i in 0 1; do
     -workDir:"${jtwork_dir}" \
     -reportDir:"${report_dir}" \
     -jdk:${JDK_TO_TEST} \
+    -vmoption:-Dtest.boot.jdk=${BOOTJDK_HOME} \
+    -vmoption:-XX:MaxRAMPercentage=25 \
     ${on_retry:-} $@ \
       && exit_code=0 || exit_code=$?
 
