d/t/jtreg-autopkgtest.in: add check for BOOT_JDK.

diff --git a/debian/tests/jtreg-autopkgtest.in b/debian/tests/jtreg-autopkgtest.in
--- a/debian/tests/jtreg-autopkgtest.in
+++ b/debian/tests/jtreg-autopkgtest.in
@@ -39,6 +39,11 @@ if [ ! -x "${JDK_TO_TEST}/bin/java" ]; then
   exit 1
 fi
 
+if [ ! -x "${BOOTJDK_HOME}/bin/java" ]; then
+  echo "Error: '${BOOTJDK_HOME}/bin/java' is not an executable." >&2
+  exit 1
+fi
+
 # restrict the tests to a few archs (set from debian/rules)
 if ! echo "${host_arch}" | grep -qE "^($(echo @jtreg_archs@ | tr ' ' '|'))$"; then
   echo "Error: ${host_arch} is not on the jtreg_archs list, ignoring it."
