* OpenJDK 14 snapshot, build 13.   * Properly generate Breaks: rules for bionic (fix typo).   * Remove libgtk-3-dev from build-deps: libgtk-3-dev is not actually     required, package builds fine without it; libgtk2.0-0 or libgtk-3-0     should be explicitly declared instead in bdeps and tests;     libxrandr-dev should be explicitly added as it is required and was     being included due to libgtk-3-dev dependency.   * Set minimum dependency on jtreg based on testsuite requirements.   * Fail during pre-build if installed jtreg version is lower then     the minimum required version.   * Improve and fix build tests and autopkgtests:     - Depend on default-jre-headless so jtreg will use the       JRE from /usr/default-java; remove JT_JAVA exports as it       no longer needs to be set.     - Update debian/tests/hotspot,jdk,langtools to ignore       jtreg-autopkgtest.sh return code.     - Create debian/tests/jtdiff-autopkgtest.in as it depends       on debian/rules variables.     - debian/tests/jtreg-autopkgtest.sh:       + Enable retry of failed tests to trim out flaky tests.       + Fix unbound variable.       + Keep .jtr files from failed tests only.     - debian/tests/jtdiff-autopkgtest.sh:       + Fail only if an actual regression is detected.       + Add the super-diff comparison from jtdiff.     - debian/rules:       + Preserve all JTreport directories in the test output         directory.       + Use JDK_DIR instead of JDK_TO_TEST for autopkgtest         generation.       + Package all .jtr files from JTwork as jtreg-autopkgtest.sh         makes sure it contains only failing tests.   * Bump standards version.   * Try to build zero on armhf again.

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -177,7 +177,7 @@ altzero_archs = $(hotspot_archs)
 ifneq (,$(filter $(distrel),trusty))
   altzero_archs := $(filter-out arm64, $(hotspot_archs))
 endif
-altzero_archs := $(filter-out armhf, $(hotspot_archs))
+#altzero_archs := $(filter-out armhf, $(hotspot_archs))
 
 ifneq (,$(filter noaltzero, $(DEB_BUILD_OPTIONS)))
   altzero_archs =
@@ -289,12 +289,12 @@ else ifneq (,$(filter $(distrel),stretch))
 else ifneq (,$(filter $(distrel),artful bionic))
   export CC = $(DEB_HOST_GNU_TYPE)-gcc-7
   export CXX = $(DEB_HOST_GNU_TYPE)-g++-7
-else ifneq (,$(filter $(distrel),precise trusty xenial))
+else ifneq (,$(filter $(distrel),buster precise trusty xenial bionic cosmic disco))
   export CC = $(DEB_HOST_GNU_TYPE)-gcc-8
   export CXX = $(DEB_HOST_GNU_TYPE)-g++-8
 else
-  export CC = $(DEB_HOST_GNU_TYPE)-gcc-8
-  export CXX = $(DEB_HOST_GNU_TYPE)-g++-8
+  export CC = $(DEB_HOST_GNU_TYPE)-gcc-9
+  export CXX = $(DEB_HOST_GNU_TYPE)-g++-9
 endif
 
 ifneq (,$(filter $(distrel),squeeze lucid))
@@ -589,11 +589,13 @@ else ifneq (,$(filter $(distrel),stretch))
   bd_gcc = g++-6,
 else ifneq (,$(filter $(distrel),artful bionic))
   bd_gcc = g++-7,
-else ifneq (,$(filter $(distrel),precise trusty xenial))
+else ifneq (,$(filter $(distrel),precise))
   # FIXME: ftbfs on armhf with the default GCC
   bd_gcc = g++-8,
+else ifneq (,$(filter $(distrel),buster bionic cosmic disco))
+  bd_gcc = g++-8 <!cross>,
 else
-  bd_gcc = g++-8,
+  bd_gcc = g++-9 <!cross>,
 endif
 bd_syslibs = zlib1g-dev, libattr1-dev,
 ifneq (,$(filter $(distrel),squeeze lucid))
@@ -608,8 +610,8 @@ bd_syslibs += \
 bd_openjdk = \
 	libxtst-dev, libxi-dev, libxt-dev, libxaw7-dev, libxrender-dev, libcups2-dev, \
 	libasound2-dev, liblcms2-dev, libfreetype6-dev (>= 2.2.1), \
-	libxinerama-dev, libkrb5-dev, xsltproc, libpcsclite-dev, libgtk-3-dev, \
-	libelf-dev, libfontconfig1-dev,
+	libxinerama-dev, libkrb5-dev, xsltproc, libpcsclite-dev, libxrandr-dev, \
+	libelf-dev, libfontconfig1-dev, libgtk2.0-0 | libgtk-3-0,
 
 pkg_ffidev = libffi-dev
 
@@ -638,8 +640,11 @@ ifeq (,$(filter $(distrel),precise))
   nocheck_profile = $(EMPTY) <!nocheck>
 endif
 
+# look at all TEST.ROOT for the required jtreg version, sorted by newest
+min_jtreg_version := $(shell find test/ -name TEST.ROOT -exec grep -hr "^requiredVersion=" {} \; | sed -e 's:^requiredVersion=::' -e 's:$$:-0~:' | sort -uVr | head -n1 | tr ' ' '-')
+
 bd_check = \
-  jtreg$(nocheck_profile) (>= 4.2-b12-1~), testng$(nocheck_profile), \
+  jtreg (>= $(min_jtreg_version))$(nocheck_profile), testng$(nocheck_profile), \
   xvfb$(nocheck_profile), xauth$(nocheck_profile), \
   xfonts-base$(nocheck_profile), libgl1-mesa-dri [!x32]$(nocheck_profile), \
   xfwm4$(nocheck_profile), x11-xkb-utils$(nocheck_profile), \
@@ -717,12 +722,12 @@ else
 endif
 
 jrehl_breaks = clojure1.8 (<= 1.8.0-7ubuntu1~),
-ifneq (,$(filter $(distrel),buster sid bionc cosmic disco eoan))
+ifneq (,$(filter $(distrel),buster sid bionic cosmic disco eoan))
   jrehl_breaks += \
 	jetty9 (<< 9.4.15-1~), netbeans (<< 10.0-3~), visualvm (<< 1.4.2-2~), \
 	eclipse-platform (<< 3.8.1-11),
 endif
-ifneq (,$(filter $(distrel),bionc cosmic disco eoan))
+ifneq (,$(filter $(distrel),bionic cosmic disco eoan))
   jrehl_breaks += \
 	tomcat8 (<< 8.5.39-1ubuntu1~),
 endif
@@ -796,7 +801,7 @@ control_vars += '-Vjcommon:Depends=$(pkg_jcommon)'
 
 control_vars += '-Vjrehl:Breaks=$(jrehl_breaks)'
 
-debian/control: debian/control.in debian/rules
+debian/control: debian/control.in debian/tests/control debian/rules
 	@cp -p debian/control debian/control.old
 	sed \
 	      -e 's/@basename@/$(basename)/g' \
@@ -831,14 +836,20 @@ debian/control: debian/control.in debian/rules
 	  exit 1; \
 	fi
 
+debian/tests/control: debian/tests/control.in debian/rules
+	sed \
+		-e 's/@min_jtreg_version@/$(min_jtreg_version)/g' \
+		$< > $@;
+
 debian/tests/%.sh: debian/tests/%.in debian/rules
 	sed \
-		-e 's,@JDK_TO_TEST@,/$(basedir),g' \
+		-e 's,@JDK_DIR@,/$(basedir),g' \
 		-e 's/@jtreg_archs@/$(jtreg_archs)/g' \
+		-e 's:@doc_dir@:/usr/share/doc/$(p_jrehl)/:g' \
 		$< > $@;
 	chmod +x $@
 
-gen-autopkgtests: debian/tests/jtreg-autopkgtest.sh
+gen-autopkgtests: debian/tests/jtdiff-autopkgtest.sh debian/tests/jtreg-autopkgtest.sh
 
 packaging-files:
 	for f in debian/*.in; do \
@@ -971,6 +982,12 @@ build_stamps = \
 build_stamps +=  stamps/jtreg-check-default
 
 pre-build:
+	jtreg_version="$$(dpkg-query -f '$${Version}\n' -W jtreg)"; \
+	if ! dpkg --compare-versions $(min_jtreg_version) le $$jtreg_version; then \
+	  echo "Error: testsuite requires jtreg $(min_jtreg_version) but $$jtreg_version is installed"; \
+	  echo "Please update the jtreg dependency and regenerate debian/control"; \
+	  false; \
+	fi
 ifneq (,$(filter $(DEB_HOST_ARCH),s390))
 	@echo explicitely fail the build for $(DEB_HOST_ARCH), patches not updated
 #else ifneq (,$(filter $(DEB_HOST_ARCH),armel))
@@ -1070,13 +1087,10 @@ ifneq (,$(filter $(VMNAME), $(with_jtreg_check)))
 	@echo "END jtreg-summary-$(VMNAME)"
 
 	-for i in hotspot langtools jaxp jdk; do \
-	  test -f jtreg-test-output/check-$$i-$(VMNAME).log || continue; \
-	  for t in $$(egrep '^(FAILED|Error)' jtreg-test-output/check-$$i-$(VMNAME).log | grep -v '^Error: Some tests failed or other problems occurred.$$' | sed -e 's/.* \(.*\)\.[^.#]\+\(#id[0-9]*\)\?$$/\1\2/' -e 's/#id/_id/'); do \
-	    echo jtreg-test-output/$$i/JTwork/$$t.jtr; \
-	  done; \
+	  find jtreg-test-output/$$i/JTwork/ -name '*.jtr'; \
 	done | sort -u > jtreg-test-output/failed_tests-$(VMNAME).list; \
 	GZIP=-9vn tar --ignore-failed-read -C . -c -z -f jtreg-test-output/failed_tests-$(VMNAME).tar.gz -T jtreg-test-output/failed_tests-$(VMNAME).list
-	GZIP=-9vn tar -C . -c -z -f jtreg-test-output/jtreport-$(VMNAME).tar.gz jtreg-test-output/*/JTreport/
+	GZIP=-9vn tar -C . -c -z -f jtreg-test-output/jtreport-$(VMNAME).tar.gz $$(find jtreg-test-output -name JTreport)
 else
 	echo "jtreg harness not run for this build" > jtreg-test-output/jtreg_output-$(VMNAME)
 endif
@@ -1089,26 +1103,26 @@ TESTS_TO_RUN = $(addprefix check-,$(TEST_SUITES))
 check-hotspot: stamps/build
 	mkdir -p jtreg-test-output/hotspot
 	JTREG_OPTIONS=$(JTREG_OPTIONS) VMNAME=$(VMNAME) JDK_TO_TEST=$(builddir)/$(sdkimg) \
-	AUTOPKGTEST_TMP=/tmp/ AUTOPKGTEST_ARTIFACTS=jtreg-test-output/hotspot/ \
+	AUTOPKGTEST_TMP=/tmp/ AUTOPKGTEST_ARTIFACTS=jtreg-test-output/ \
 	  $(TIME) debian/tests/hotspot | tee jtreg-test-output/$@.log
 
 
 check-langtools: stamps/build
 	mkdir -p jtreg-test-output/langtools
 	JTREG_OPTIONS=$(JTREG_OPTIONS) VMNAME=$(VMNAME) JDK_TO_TEST=$(builddir)/$(sdkimg) \
-	AUTOPKGTEST_TMP=/tmp/ AUTOPKGTEST_ARTIFACTS=jtreg-test-output/langtools/ \
+	AUTOPKGTEST_TMP=/tmp/ AUTOPKGTEST_ARTIFACTS=jtreg-test-output/ \
 	  $(TIME) debian/tests/langtools | tee jtreg-test-output/$@.log
 
 check-jaxp: stamps/build
 	mkdir -p jtreg-test-output/jaxp
 	JTREG_OPTIONS=$(JTREG_OPTIONS) VMNAME=$(VMNAME) JDK_TO_TEST=$(builddir)/$(sdkimg) \
-	AUTOPKGTEST_TMP=/tmp/ AUTOPKGTEST_ARTIFACTS=jtreg-test-output/langtools/ \
+	AUTOPKGTEST_TMP=/tmp/ AUTOPKGTEST_ARTIFACTS=jtreg-test-output/ \
 	  $(TIME) debian/tests/jaxp | tee jtreg-test-output/$@.log
 
 check-jdk: stamps/build
 	mkdir -p jtreg-test-output/jdk
 	JTREG_OPTIONS=$(JTREG_OPTIONS) VMNAME=$(VMNAME) JDK_TO_TEST=$(builddir)/$(sdkimg) \
-	AUTOPKGTEST_TMP=/tmp/ AUTOPKGTEST_ARTIFACTS=jtreg-test-output/jdk/ \
+	AUTOPKGTEST_TMP=/tmp/ AUTOPKGTEST_ARTIFACTS=jtreg-test-output/ \
 	  $(TIME) debian/tests/jdk | tee jtreg-test-output/$@.log
 
 jtregcheck: $(TESTS_TO_RUN)
@@ -1776,11 +1790,10 @@ endif
 
 is_release		= yes
 is_release		=
-hg_project		= jdk11u
+hg_project		= jdk14u
 hg_tag			= jdk-11.0.1+13
-hg_project		= jdk13
 hg_project		= jdk
-hg_tag			= jdk-14+6
+hg_tag			= jdk-14+13
 package_version		= $(subst jdk-,,$(hg_tag))
 ifneq ($(is_release),yes)
   package_version	:= $(subst +,~,$(package_version))
